7 спринт: реализовать файловый трекер задач
elistratov-av/java-kanban pull request #2
Opened 2024-05-17 21:34 UTC by elistratov-av

2024-05-18 04:15 UTC, sergeymamonov requested changes

2024-05-18 04:15 UTC, sergeymamonov commented on src/services/FileBackedTaskManager.java
> +        }
Лучше добавить default.

2024-05-18 04:15 UTC, sergeymamonov commented on src/services/FileBackedTaskManager.java
> +        switch (task.getType()) {
Здесь может быть NPE, когда придет task равный null.

2024-05-18 04:15 UTC, sergeymamonov commented on src/utils/ManagerSaveException.java
> +    public ManagerSaveException() {
Если конструктор не используется, то лучше его удалить.

2024-05-18 04:15 UTC, sergeymamonov commented on src/utils/StringUtils.java
> +    public static String trim(String s) {
Используется ли где-то этот метод?

2024-05-18 04:15 UTC, sergeymamonov commented on src/utils/TaskComparator.java
> +public class TaskComparator implements Comparator<Task> {
А зачем потребовался этот компаратор?

2024-05-18 04:15 UTC, sergeymamonov commented on src/utils/StringUtils.java
> +    public static int compare(String s1, String s2, boolean nullAsEmpty) {
Для чего нужен этот метод?

2024-05-18 04:15 UTC, sergeymamonov commented on src/utils/TaskCsvConverter.java
> +    private static Task fromCsv(Task task, String[] tokens) {
Дело вкуса, но я бы назвал как-то по другому (values, fields, ...).

2024-05-18 04:15 UTC, sergeymamonov commented on src/utils/TaskCsvConverter.java
> +        if (tokens.length > 2) {
Всю эту логику со сравнением длины, лучше постараться переделать. То есть мы получаем строку, например, типа id, , , description. И лучше получить массив типа [id, null, null, description]. И тогда не нужна будет куча if (tokens.length > 3).

2024-05-18 05:37 UTC, elistratov-av commented on src/services/FileBackedTaskManager.java
> +        }
добавил IllegalStateException

2024-05-18 05:47 UTC, elistratov-av commented on src/services/FileBackedTaskManager.java
> +        switch (task.getType()) {
метод приватный, а перед его вызовом делаю проверку на null. тут на самом деле не знаю что лучше, если внести проверку внутрь, то генерить исключение на мой взгляд неправильно, хотя с другой стороны это можно будет рассматривать как обязательную проверку по типу забыл на входе проверить получи исключение, но в таком случае что NPE, что какое-то другое исключение будут равноценны. можно сделать проверку и если null просто вернуться из метода сразу. в данном конкретном варианте использования, когда после загрузке больше никаких действий не делается, а происходит переход на другую итерацию, такой подход будет хорошим. а если бы после загрузки требовались какие-то другие дополнительные действия, то тогда как быть, возвращать булево значение ?
просто я в таких случаях предпочитаю выкинуть исключение. сейчас просто добавил проверку, но как быть в общем случае я не знаю. честно говоря вариант с NPE мне кажется нормальным, такой вариант можно трактовать либо забыл проверить на входе, либо нарушена логика обработки данных и выбросилось исключение.

2024-05-18 05:51 UTC, elistratov-av commented on src/utils/ManagerSaveException.java
> +    public ManagerSaveException() {
для исключений я предпочитаю создавать обязательную тройку конструкторов, в том числе и конструктор по умолчанию. в данном текущем задании он не используется, но я рассматриваю его как общий код, который шире конкретного задания и предпочитаю оставить полный набор конструкторов

2024-05-18 05:57 UTC, elistratov-av commented on src/utils/StringUtils.java
> +    public static String trim(String s) {
нет не используется, вначале я хотел его применить при обработке токенов при чтении из файла, но потом подумал, что лучше так не делать, если кто-то за пределами программы внесет изменения в файл, то это уже несанкционированный доступ, а лишние пробелы могли появится и по реальным причинам в имени задачи. просто метод сам по себе очень удобен на практике, мне например непонятно почему в Java такой метод отсутствует в виде статического метода, чтобы не заморачиваться с проверками на null у строк. пусть остается, может в слдующих задачах пригодится, если это будет принципиально, то готов его убрать

2024-05-18 05:58 UTC, elistratov-av commented on src/utils/StringUtils.java
> +    public static int compare(String s1, String s2, boolean nullAsEmpty) {
этот метод используется в main для сравнения массивов задач
System.out.println("Списки задач обоих трекеров совпадают: " + Arrays.equals(tasks1, tasks2, new TaskComparator()));

2024-05-18 05:59 UTC, elistratov-av commented on src/utils/TaskCsvConverter.java
> +    private static Task fromCsv(Task task, String[] tokens) {
я рассматриваю этот алгоритм как парсинг строковых данных, поэтому и назвал как tokens

2024-05-18 14:30 UTC, elistratov-av commented on src/utils/TaskComparator.java
> +public class TaskComparator implements Comparator<Task> {
в main реализован расширенный вариант задания и в нем необходимо сравнить исходный набор задач с загруженными из файла. сравнение с опорой на реализованный метод equals не подходит, поскольку критерием равенства объектов в нем служит равенство их ключей (поле id), а необходимо выполнить сравнение по всем полям

2024-05-18 17:19 UTC, elistratov-av commented on src/utils/TaskCsvConverter.java
> +        if (tokens.length > 2) {
переделал и убрал вложенные if, но первоначальный способ более устойчив к входному формату данных
я бы наверное избавился от вложенности, но оставил бы пошаговую проверку массива токенов

2024-05-20 03:27 UTC, sergeymamonov commented on src/services/FileBackedTaskManager.java
> +        switch (task.getType()) {
Если где-то в ходе работы программы возникает NPE, то это ошибка программиста. NPE возникать не должно. Лучше всегда в коде проверять получаемые значения. Что делать дальше с результатом - зависит от контекста и бизнес требований. В данном случае мы получили таску, но по факту вместо таски получили null. Я бы разсценивал это как нарушение бизнес логики и сразу бы об этом сигнализировал. 

if (task == null) return; - сигнала о нарушении бизнес логики не дает, а показывает, что это нормальная ситуации. Поэтому я бы переделал на выброс исключения в этом месте.

2024-05-20 03:27 UTC, sergeymamonov commented on src/utils/ManagerSaveException.java
> +    public ManagerSaveException() {
В коде не должно быть неиспользуемого кода. Иначе через какое-то время код невозможно будет читать. Уже будет непонятно, какой код используется, а какой нет. И для чего этот код оставлен. Это сейчас проект небольшой. Реальные проекты значительно больше. И если там не придерживаться таких рассуждений, и оставлять ненужный код, то достаточно скоро код можно будет выбросить и начать писать проект заново.

2024-05-20 03:29 UTC, sergeymamonov commented on src/utils/StringUtils.java
> +    public static String trim(String s) {
Нет, это неправильно. Неискользуемого кода в программе быть не должно. Когда потребуется, тогда и добавите. Есть система контроля версий, код легко будет взять из предыдущих коммитов. Но в главной ветке неиспользуемого кода быть не должно.

2024-05-20 03:32 UTC, sergeymamonov commented on src/utils/TaskComparator.java
> +public class TaskComparator implements Comparator<Task> {
Так переопределите метод equals, это значительно легче, и не нужно будет писать целый класс компаратора. И главное логика не размазывается по всему приложению. Есть класс таск и в нем методы требующиеся для этого класса: геттеры, сеттеры, метод сравнения и так далее.

2024-05-20 03:38 UTC, sergeymamonov commented on src/utils/StringUtils.java
> +    public static int compare(String s1, String s2, boolean nullAsEmpty) {
См. комментарий выше про метод equals в классе таск.

2024-05-20 03:41 UTC, sergeymamonov commented on src/utils/TaskCsvConverter.java
> +        if (tokens.length > 2) {
Когда количество полей будет расти, то будет расти и количество if, и код станет не читаемым. Достаточно одной проверки, что количество полей равно определенному количеству. И если меньше, то кидать ошибку.

2024-05-20 03:42 UTC, sergeymamonov approved these changes

2024-05-20 06:54 UTC, merged