8 спринт: добавить к задачам время и длительность
elistratov-av/java-kanban pull request #3
Opened 2024-05-30 20:30 UTC by elistratov-av

2024-05-31 04:25 UTC, sergeymamonov requested changes
ManagerSaveException - оставить только используемые конструкторы.

2024-05-31 04:25 UTC, sergeymamonov commented on src/tasks/Task.java
> +public class Task implements Cloneable {
А зачем здесь нужен этот интерфейс?

2024-05-31 04:25 UTC, sergeymamonov commented on test/services/InMemoryTaskManagerTest.java
>  }
Тестовый класс без тестов.

2024-05-31 06:46 UTC, elistratov-av commented on src/tasks/Task.java
> +public class Task implements Cloneable {
убрал лишние конструкторы
интерфейс добавил поскольку при сохранении задач в историю я их клонирую, раньше использовал конструктор копии, но подумал, что метод clone будет лаконичней и удобнее

2024-05-31 06:52 UTC, elistratov-av commented on test/services/InMemoryTaskManagerTest.java
>  }
class InMemoryTaskManagerTest extends TaskManagerTest<InMemoryTaskManager>
по заданию просили вынести все общие тесты для двух менеджеров в базовый класс, чтобы не дублировать код
поэтому для InMemoryTaskManagerTest все тесты лежат в базовом классе (он абстрактный и для его работы требуется задать переменную taskManager, тип которой определяется в производном классе)
а для FileBackedTaskManagerTest добавил тесты уникальные для его реализации, связанные с работой с файлами

2024-06-01 08:01 UTC, sergeymamonov approved these changes

2024-06-01 09:44 UTC, merged